PROXY_HOST = ""
PROXY_PORT = ""
PROXY_USER = ""
PROXY_PASS = ""
SECRET_KEY = ""

LAST_ITEMS_MAX_SIZE: int = 1000
REQUEST_TIMEOUT: int = 30000
MAX_RETRIES: int = 3
USER_AGENT_ROTATION_INTERVAL: int = 50
